CREATE TABLE grade
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject    VARCHAR(255),
    score      INTEGER                                 NOT NULL,
    student_id BIGINT,
    CONSTRAINT pk_grade PRIMARY KEY (id)
);

CREATE TABLE student
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE grade
    ADD CONSTRAINT FK_GRADE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);
